// Generated by Unloop
// Office Thermostat

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_quick_heat_clicked(|| {
        println!("quick_heat clicked");
    });
    
    app.on_work_mode_clicked(|| {
        println!("work_mode clicked");
    });
    

    
    app.run()
}
